# Generated by Django 4.1 on 2022-11-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField(max_length=2000)),
                ('fechapublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen01', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
