# Generated by Django 4.1.2 on 2022-11-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_entrenamientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamientos',
            name='ejercicios',
            field=models.CharField(default='no hay rutina todavía', max_length=80),
        ),
    ]
