# Generated by Django 4.1.2 on 2022-11-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0003_entrenamientos_ejercicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamientos',
            name='intensidad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'media'), ('baja', 'baja')], max_length=10),
        ),
    ]
