# Generated by Django 4.1.2 on 2022-11-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0004_alter_entrenamientos_intensidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicios', models.CharField(default='no hay rutina todavía', max_length=80)),
            ],
        ),
    ]
