# Generated by Django 4.1.2 on 2022-11-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_fichasocio_delete_administrador'),
        ('About', '0006_remove_entrenamientos_intensidad'),
    ]

    operations = [
    ]
