# Generated by Django 4.1.2 on 2022-11-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0007_merge_20221116_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamientos',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2),
        ),
    ]
