# Generated by Django 4.1.2 on 2022-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0008_alter_entrenamientos_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('día', models.CharField(choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mier', 'Miércoles'), ('Jue', 'Jueves'), ('Vier', 'Viernes')], max_length=5)),
                ('sede', models.CharField(choices=[('B', 'Belgrano'), ('N', 'Nuñez'), ('P', 'Palermo')], max_length=5)),
                ('clase', models.CharField(choices=[('Y', 'Yoga'), ('M', 'Meditación')], max_length=5)),
                ('horario', models.CharField(choices=[('8', '8 hs'), ('9', '9 hs'), ('10', '10 hs'), ('11', '11 hs'), ('12', '12 hs')], max_length=5)),
            ],
        ),
    ]
