# Generated by Django 4.1.2 on 2022-11-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0009_horarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenamientos',
            name='ejercicios',
        ),
    ]
