# Generated by Django 4.1.2 on 2022-11-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0011_alter_horarios_clase_alter_horarios_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='día',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10),
        ),
    ]
