# Generated by Django 4.1.2 on 2022-11-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0012_alter_horarios_día'),
    ]

    operations = [
        migrations.CreateModel(
            name='recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida', models.CharField(max_length=200)),
                ('ingredientes', models.CharField(max_length=200)),
                ('preparación', models.TextField(max_length=2000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('receta_imagen', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
